spring:
  application:
    name: ApiGateway

  zipkin:
    base-url: http://localhost:9411/
  cloud:
    gateway:
      routes:
      - id: bookcommand
        uri: lb://bookcommand
        predicates:
        - Path=/books/**
      - id: customerService
        uri: lb://customerService
        predicates:
        - Path=/customer/**
      - id: bookqueryService
        uri: lb://bookqueryService
        predicates:
        - Path=/bookquery/**
      - id: borrowingService
        uri: lb://borrowingService
        predicates:
        - Path=/borrow/**
      - id: reviewService
        uri: lb://reviewService
        predicates:
        - Path=/review/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
